### ISSUE TITLE
Missing non-required IDType breaks validation

### ISSUE THREAD

**Issue by brian-r-calder** [CCOMJHC/csbschema#17]
The IDType/IDNumber elements in properties/platform are not mandatory in B.12, but having these values missing in the 3.1.0 2023-08 metadata schema causes the code to crash on validation with a KeyError.

**Comment by selimnairb** [comment]
@brian-r-calder Can you attach an example document that triggers the behavior your are seeing? Thanks.

**Comment by selimnairb** [comment]
@brian-r-calder See #16, which attempts to address this issue.
