### ISSUE TITLE
Extra information required for VerticalReduction processing metadata

### ISSUE THREAD

**Issue by brian-r-calder** [CCOMJHC/csbschema#19]
The VerticalReduction processing metadata requires 'reference', 'datum', and 'method' properties, and can have an optional 'model' property.  However, this does not capture the algorithm used to apply the vertical reduction or its version.

Therefore, add 'algorithm' and 'version' (both free text) as optional properties in the schema (384:418 in 3.1.0 2023-08).

**Comment by selimnairb** [comment]
@brian-r-calder See #16, which attempts to address this issue.
